### ISSUE TITLE
W10

### ISSUE THREAD

**Issue by SambaEdu** [SambaEdu/se3-domain#1]
## **Installation** et personnalisation

Images m$ w10
https://www.ntlite.com/download/

ntlite
https://www.ntlite.com/download/

Rufus (pour mettre l'iso sur clé usb bootable)
https://rufus.akeo.ie/?locale=fr

## Profils 

Rendre un profil local errant
https://community.spiceworks.com/how_to/4006-customize-the-default-domain-user-profile
[Default User.V6.zip](https://github.com/SambaEdu/se3-domain/files/643491/Default.User.V6.zip)

Gestion / copie profil w8 --->  w10  à tester avec l'outil  ProfileTool
http://www.it-connect.fr/personnaliser-le-profil-utilisateur-par-defaut-sous-windows-8/

préco m$ : 
https://msdn.microsoft.com/fr-fr/library/windows/hardware/dn898521(v=vs.85).aspx

Structure du profil en détails
http://sospc.name/cloner-reparer-compte-utilisateur/

**Comment by jlcf** [comment]
Reparation du compte local administrateur :
[repare-compte-local-administrateur-w10.reg.zip](https://github.com/SambaEdu/se3-domain/files/643722/repare-compte-local-administrateur-w10.reg.zip)

**Comment by SambaEdu** [comment]
Clés de registre pour w10 :
[Win10-Samba44-reg.zip](https://github.com/SambaEdu/se3-domain/files/721594/Win10-Samba44-reg.zip)

**Comment by SambaEdu** [comment]
Intégration des fichiers reg ok :
- repare-compte-local-administrateur-w10.zip
- Win10-Samba44-reg.zip
